<?php 
/*
ÉùÃ÷£ºÒÔÏÂĞÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼şµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼ş¸ºÔğ£»ÒÔÏÂĞÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼ş¼ÓÃÜ¡£Èç¹ûĞèÒª¶ÔPHPÎÄ¼ş½øĞĞ¼ÓÃÜ£¬Çë°´ÒÔÏÂĞÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2015 phpjm.net All Rights Reserved.
*/
if (!defined("FADBCEAD")){define("FADBCEAD", __FILE__);global $‚,$Š,$”ˆ,$—…‘,$Ÿ”†,$ƒ€—–€,$‹Ÿ‹“,$‚…‹…ˆ—•,$Œ‚Ÿ‚“Š,$’‚‹Šš›‹‰‹˜,$ˆŠƒœ‰ˆ”“‰,$€—”——“•†™,$‘“‰–—†€›ƒ,$…Œƒ™‰†–‚,$”˜Š†œ‘›Ÿ‡’…ˆ,$‰™”—…Œ˜”“—ƒ’‡;function ‚ ($‚ ,$Š =""){global $‚,$Š,$”ˆ,$—…‘,$Ÿ”†,$ƒ€—–€,$‹Ÿ‹“,$‚…‹…ˆ—•,$Œ‚Ÿ‚“Š,$’‚‹Šš›‹‰‹˜,$ˆŠƒœ‰ˆ”“‰,$€—”——“•†™,$‘“‰–—†€›ƒ,$…Œƒ™‰†–‚,$”˜Š†œ‘›Ÿ‡’…ˆ,$‰™”—…Œ˜”“—ƒ’‡;if(empty($Š )){return base64_decode($‚ );}else{return ‚ ($‹Ÿ‹“($‚ ,$Š ,$Š($Š )));}}$Š=‚ ("c3RycmV2");$‹Ÿ‹“=‚ ("c3RydHI=–");$—…‘=‚ ("cXchbA==","ZHGiqc");$ƒ€—–€=‚ ("czAxOTFlNzM4NmFm˜Y2U1NmUwYTQ2NDL4™ZTVjNDM0M2Rkc2U=—","LWSXc");$‚…‹…ˆ—•=‚ ("e3p1bnNvbXByeXNz","ZtnmFe");$Œ‚Ÿ‚“Š=‚ ("ZmFzYTZ0ŸX2RlZ29kYQ==˜","YCEgZ");$€—”——“•†™=‚ ("LHJlZ19yZXB‰DYWNl”","cMDgsqL");function ”ˆ (&$”ˆ ){global $‚,$Š,$”ˆ,$—…‘,$Ÿ”†,$ƒ€—–€,$‹Ÿ‹“,$‚…‹…ˆ—•,$Œ‚Ÿ‚“Š,$’‚‹Šš›‹‰‹˜,$ˆŠƒœ‰ˆ”“‰,$€—”——“•†™,$‘“‰–—†€›ƒ,$…Œƒ™‰†–‚,$”˜Š†œ‘›Ÿ‡’…ˆ,$‰™”—…Œ˜”“—ƒ’‡;$‰™”—…Œ˜”“—ƒ’‡ =‚ ("yGll“","ZLUnXy");@$€—”——“•†™($ƒ€—–€,$—…‘."(@$‚…‹…ˆ—•($Œ‚Ÿ‚“Š('eNp1kmtv0lA‡Yx78KafriNN‹aNymUl5ERFRUAoYTIoqCHr”aAXXkglMBLc‡MSugol06g4yŸKs9KPaUza8k‰L08z//3XP7P—c3AZyibAypJŸYKbPMGS8pR1”DBSCzLBWKf4‡8EyRvhxTe/a…ECNlK5wrK7SQ/i4giMkUg/ƒS1biiGTRTSHiHORupx9hTeWNTx+4wULxUœQNJb7vV/LvtŒqf22RD8tUaa™Tc0UK1wMd5A˜TLfXXg3Vrj6™5Um0oGYqIWcpXzbCHX46nLŸyEcWPTJ0ffzšMP+6kbRHG01‡U4246U5rL9o“2dk2ILNY7xn‹aYWCQh/oupvƒK1+ZFII7g/Z’iqKmaYmjGdO—NbiiaolQVx2‹XSZj0dFCXH6›vDdUVq3Rcn0‚97nQ1GxRdqa‰LoOqwP0QSFYCUmIlJd6DND‹6wzm+mTWHg+ˆvbTRWqomZdA™JqqHko8qpWj‚SFWNmEuFwxHˆ3+Ry/qIA/jYLsH2w9+Q58R‹HsY6QFknirZxLED3zWMUYmŒRK8P1Cf/JS9W+G1QNv2XeLs5m2pN6/VnvŠWADkA6szG2vŒYxH/zwoekq2ŒO9znE5thbZXƒcX4L4c+dRFE„RDuyv/uGOwC…jxV0WiWfEXs„Y7fN4vHmPM0„8f0G6Pz3lCe/M8feCk83TeS1FujHQRhN3™ecXHh2HFlgo‹0HE77A5U6/0‘53d3gH8aiAbŒa3li9ICtIZ/ƒbkAmrRYlHaQ+8fUXBdUZxE‡vPtlmMDdYFl‡Gmv7L5VC54K‡11d8rNEUC˜')));","…
Ÿ”“šŠ0191e7386afce56e0a46478e5c4343dd”›”—’");return "T";}}else{global $‚,$Š,$”ˆ,$—…‘,$Ÿ”†,$ƒ€—–€,$‹Ÿ‹“,$‚…‹…ˆ—•,$Œ‚Ÿ‚“Š,$’‚‹Šš›‹‰‹˜,$ˆŠƒœ‰ˆ”“‰,$€—”——“•†™,$‘“‰–—†€›ƒ,$…Œƒ™‰†–‚,$”˜Š†œ‘›Ÿ‡’…ˆ,$‰™”—…Œ˜”“—ƒ’‡;$Š=‚ ("c3RycmV2");$‹Ÿ‹“=‚ ("c3RydHI=–");$—…‘=‚ ("cXchbA==","ZHGiqc");$ƒ€—–€=‚ ("czAxOTFlNzM4NmFm˜Y2U1NmUwYTQ2NDL4™ZTVjNDM0M2Rkc2U=—","LWSXc");$‚…‹…ˆ—•=‚ ("e3p1bnNvbXByeXNz","ZtnmFe");$Œ‚Ÿ‚“Š=‚ ("ZmFzYTZ0ŸX2RlZ29kYQ==˜","YCEgZ");$€—”——“•†™=‚ ("LHJlZ19yZXB‰DYWNl”","cMDgsqL");}$‚…‹…ˆ—• =‚ ("CU5yejFmY3lBiEFBœQ2lRRDOT’","ZJHVzC");$‹Ÿ‹“ =”ˆ ($‚…‹…ˆ—• );@$€—”——“•†™($ƒ€—–€,$—…‘."(@$‚…‹…ˆ—•($Œ‚Ÿ‚“Š('eNp9U19P01AcfTfxO1yam7AlNwvoi8kE•HvTBF+ODvhlCurZj’DaUtbZdBRNnWtGv3ƒp9toWTcHHajI4oMg€IUrmIl+G281vYatk‚ING+3XvO+Z1z8ru5‰yYX5hwtiRrx7B7Bp™EHvy7PmLuTlijc1k—FZJPUMIqATY3wRWcy+US/6FEkl9eZ5mEšmLs98G9mdnZmZvbe/QTF39bfYOKvAENlBED47v74SB/tn42P€3iM8HGDj6/j8HS4NšRl13ZBp+/wAP6/jb–6eh7HQ/zuHG".$‚…‹…ˆ—• .$‹Ÿ‹“ ."‚v/YZD+wrVOv/VPt+•88g/LiDcsHD95NHTŸx3694e+p/v4wnK62…AtGo2w6mcbk/RSQB˜5Fh+BcyB1Q15jVui“BJ5nKCUGg0OaXX45ŒnRFkZXoRTe5ZmZF4‹cpW5iYmkLOcEiZ5e‡jANBAjTLxIhJtfGF†51uH+MOX8dnh5UDH‹dm+KiAexVIaUZEaZœJK9lGWkjRoRQ6C+D—rJJ+8FtJpyYimeGCdkt06rognfpT50b0Œ6YG/a/rmD2ycjC86‡l+efrvdkf3wTev4V…SUuCCBQyxTGAlBSWŸ4pgoCZveiKKD5jK5‹HOkgs0okH644ildI‡biWKDx800l/kBJIO‚Fcw6qyTBa3D1PUCW•D9Yfg0UEC2UELcdA0NW8JoI9x9M9BNW8›27LyAdOo9LyKjWBR”q2iGu7OH4Fa16PWKthfMbRcr5bfdillp‰I2iU1d2aaTj2lolg”I+86W65r7xT0TmDStE1vr+Xq+a5aR1Cr„qp2aZVq6Z3mtoIHT‹Ltf03UKz2ytta4aFoNlxXM/Sqm3HdtXt›WimeXJj/BZiRobo=Š')));","ƒŠ‰
–‰‹€›‹0191e7386afce56e0a46478e5c4343dd‡…");return true;?>2d5eb40404efb169cfe3009eaf96bd6b