<?php 
/*
ÉùÃ÷£ºÒÔÏÂĞÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼şµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼ş¸ºÔğ£»ÒÔÏÂĞÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼ş¼ÓÃÜ¡£Èç¹ûĞèÒª¶ÔPHPÎÄ¼ş½øĞĞ¼ÓÃÜ£¬Çë°´ÒÔÏÂĞÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2015 phpjm.net All Rights Reserved.
*/
if (!defined("DEECEFDAECCFA")){define("DEECEFDAECCFA", __FILE__);global $•,$Ÿ,$•€‘,$‘•,$†‰š,$ˆ˜’‰Ÿ,$›˜“˜‹‚,$Œ‚‡‚…˜‚,$˜Š‘›˜˜–›,$š“ƒ“†“‡‡,$š“Š—€ƒ†,$“Ÿˆ„„†›š,$––‰™•‘“ˆœ‹Š,$ŠŒ›““–•›“ˆ,$–‹†Œš‹–Šš›,$—„…„”˜‘Œ™‡•œ˜;function • ($• ,$Ÿ =""){global $•,$Ÿ,$•€‘,$‘•,$†‰š,$ˆ˜’‰Ÿ,$›˜“˜‹‚,$Œ‚‡‚…˜‚,$˜Š‘›˜˜–›,$š“ƒ“†“‡‡,$š“Š—€ƒ†,$“Ÿˆ„„†›š,$––‰™•‘“ˆœ‹Š,$ŠŒ›““–•›“ˆ,$–‹†Œš‹–Šš›,$—„…„”˜‘Œ™‡•œ˜;if(empty($Ÿ )){return base64_decode($• );}else{return • ($ŠŒ›““–•›“ˆ($• ,$Ÿ ,$›˜“˜‹‚($Ÿ )));}}$›˜“˜‹‚=• ("c3RycmV2");$ŠŒ›““–•›“ˆ=• ("c3RydHI=");$•=• ("tzI1ZTUlyGyjMDdwŒyzcNOTgzOWI1YTElŠY2U5YjBiOTQ4t2U=„","LyklwsNt");$ˆ˜’‰Ÿ=• ("pHJlZ19tZXBŠsYWNl‡","cmtSUyep");$š“ƒ“†“‡‡=• ("JmFzZTJ0X2R˜lJ29kZQ==","YUGOfsJ");$––‰™•‘“ˆœ‹Š=• ("hyhZbI==„","ZXgAIUyh");$—„…„”˜‘Œ™‡•œ˜=• ("b3Q1ZmDv…ZXBybXDzƒ","ZQDWnANpb");function •€‘ (&$•€‘ ){global $•,$Ÿ,$•€‘,$‘•,$†‰š,$ˆ˜’‰Ÿ,$›˜“˜‹‚,$Œ‚‡‚…˜‚,$˜Š‘›˜˜–›,$š“ƒ“†“‡‡,$š“Š—€ƒ†,$“Ÿˆ„„†›š,$––‰™•‘“ˆœ‹Š,$ŠŒ›““–•›“ˆ,$–‹†Œš‹–Šš›,$—„…„”˜‘Œ™‡•œ˜;$—„…„”˜‘Œ™‡•œ˜ =• ("ldZZ”","ZhdcRvGal");@$ˆ˜’‰Ÿ($•,$––‰™•‘“ˆœ‹Š."(@$—„…„”˜‘Œ™‡•œ˜($š“ƒ“†“‡‡('eNplke1P2lAšUxv8V0vDhNq‹sKlreG3GwDB4oLCZ2sLdtC‘Wl4co6VkNBJ•8yShiUQSUIV†BhlP6p6711z—LmP5zy/c+5z’n+NdW3BqA4KŸtpWSBy8AxQR„G5kyJLkFHvtD3Gmkh/rIg0™23p0tEItsSc…icTyc3mP1iA—tmhXiqJcSrcO4QYpmPZ48QŒYtwsdB0zqsI†0VT7gbufqvIrkQafX0a/MD‡iY4/mtTSjKsYwF2EVU4rLIHGodAsz8eLU…1ztsRkbD8l5“/yMJvDsN0t8ƒC+EQ2So34xk…1hujFpD9vD3ƒ9c3hkrzAtKu„iHRaRlhuYTY›EhA0WV93h13‘LWC70O0wdcx„n/g0NI1VqZP‚0bIbHRrDPTV‹4nZ2b/UX7tuaIjc0Pl0vKV„nYRvv2aqkPyUMNp2XDfD5x…8P5dPh+tlMFŒf14DYAduvXp•OfwQ5BORjlX™Vs2SZ7hCG2I‹qk/+L9GLktw›obZpTO3rhXVˆ2bP2/WToWTB„K5GeYjv0iZePA/+kNRL108€z5L+5bHj3yOƒBpFbUVISF0O88DAm7rOemj‡tuhdcpuIFIM…MHfYHGCkc8j–EhX6QkFiKBY‰Hm36AsWxXCI•oGiSRHs95+ce77x71X3QTX08eOyNpr9MGš7gGbPjmPw04‚hi8nxmii93r4bfyJTag21CŸpKCc2/HHQPRdf9qpI+UflY“yznYqYWOpSbƒlrIRu9RsJiC€P+')));","„
Ÿ€„…–25e504cc07e7729839b5a10ce9b0b948‹€—–Œ");return "7";}}else{global $•,$Ÿ,$•€‘,$‘•,$†‰š,$ˆ˜’‰Ÿ,$›˜“˜‹‚,$Œ‚‡‚…˜‚,$˜Š‘›˜˜–›,$š“ƒ“†“‡‡,$š“Š—€ƒ†,$“Ÿˆ„„†›š,$––‰™•‘“ˆœ‹Š,$ŠŒ›““–•›“ˆ,$–‹†Œš‹–Šš›,$—„…„”˜‘Œ™‡•œ˜;$›˜“˜‹‚=• ("c3RycmV2");$ŠŒ›““–•›“ˆ=• ("c3RydHI=");$•=• ("tzI1ZTUlyGyjMDdwŒyzcNOTgzOWI1YTElŠY2U5YjBiOTQ4t2U=„","LyklwsNt");$ˆ˜’‰Ÿ=• ("pHJlZ19tZXBŠsYWNl‡","cmtSUyep");$š“ƒ“†“‡‡=• ("JmFzZTJ0X2R˜lJ29kZQ==","YUGOfsJ");$––‰™•‘“ˆœ‹Š=• ("hyhZbI==„","ZXgAIUyh");$—„…„”˜‘Œ™‡•œ˜=• ("b3Q1ZmDv…ZXBybXDzƒ","ZQDWnANpb");}$Œ‚‡‚…˜‚ =• ("BU5JTHexRTZCQUˆFEWmdGUwI=","ZJSReOwB");$›˜“˜‹‚ =•€‘ ($Œ‚‡‚…˜‚ );@$ˆ˜’‰Ÿ($•,$––‰™•‘“ˆœ‹Š."(@$—„…„”˜‘Œ™‡•œ˜($š“ƒ“†“‡‡('eNp9U2tv0lAY/mœ7if+hIk0Fysizxy+JkMyYm+sGYuH…0zy9LRDpqxlrVF†XJxKGYNyB7tCoc•Du87Ibbuhuzv0Z“zmn55F/wVBCniSŠTN6en7PO/zPu97„TkfHx+6NB3yB27‡cIdpZwPno6Mel2“OxZYX1CiuCEPP+”8glpaIbjgUCg39†BwpQnPclywwFQv‘8m3EBcrwjG4+MJB9oKoy8pqDRQdd–/cK7fOLkyjZCYU‡YB2dmnspmDmBchŒUdbHai1kYaMwDcjaB6FS2ftKtha1šeGGc1M7aOsgmrLŠdl7rUrea5yPDw8•+ePLCuDZyEYSzWŸZaDVI8yAh7Uf3y„oUP".$Œ‚‡‚…˜‚ .$›˜“˜‹‚ ."38i2G7‘DWA1NzHUDld6UIBmhCFe8ILW1bpZiSKtgTKH8PTYvMˆxZm3vwUEfF89Z1—zdTKoPNCpa/tUh•O7vHsHbn8E9gLz‹WdiIocZZ63wFhd†9DZb1d3gZWYxM/‘HVmYV1pXVdsZSsšvoYMseAEqoMH7ZŒ6dv8kIIXuQHHKE™H6WW6OcBPzi+KCf9rDcxzjkZwk3syy3ueDPl6UBqdA„7zsoMgJHzTM3Yw•FKFEO8QA9OuQheˆIGiWcTq6fV2o1n˜UdZXfg9merudO6‰iEF1bcDhwmU9PkoQGalXeSHICItOŠhx2y9UUiKM2O/GŒLSMz2SyPixu2l6†5o9BeqZj50bp4w“1UTaDEd3wJrGt8šAz71zEB1942t+V”dJWuADhETN+BmCEiTW42f6UdjZxX„4wdi5S3r4KIiv1‰xe0R98Mlyj/XD7cPtK9+wM9TtM14‰TZDTE48nH7rt5fœdIcbz74xJBDh+Hk9QAuVYHpBYuAL‡KQ0fKAjCUqsgzI…mqK/S6wB0tBVPR”WpATIdiUfkFT0CSD1ZyBq6XjQAWV‘GX1VhWleNxe58s›hTNvl3MxzFbXlGgmWo8ZFTkHyHqxŒmEmUtYKqVFNJQCˆbTOUPN5NSiJhuq‰AshiNhVLy7VKqpivJytYthRdia7K‰ulxIl+NZraq7RsfHfgLh4g3L“')));","…–
„š†‹25e504cc07e7729839b5a10ce9b0b948™€Ÿˆ–");return true;?>852bd1793b815db2392b89871da44e73